name: curla
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pyparsing
  - absl-py
  - pillow
  - nvidia::cudatoolkit=11.7
  - pytorch::pytorch==1.13.1
  - pytorch::torchvision==0.14.1
  - pytorch::torchaudio==0.13.1
  - pytorch::pytorch-cuda=11.7
  - libpng
  - libjpeg-turbo
  - libtiff<4.4.0
  - pip:
    - numpy
    - psutil
    - gymnasium
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - tensorboard
    - termcolor
    - scikit-image
    - scikit-learn
    - matplotlib
    - kornia
    - carla==0.9.14