name: curla
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.7.9
  - pip
  - pyparsing
  - cudatoolkit=9.2
  - absl-py
  - pillow=6.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch==1.13.1
  - pytorch-cuda=11.7
  - pip:
    - numpy
    - gymnasium
    - imageio
    - imageio-ffmpeg
    - tqdm
    - opencv-python
    - tensorboard
    - termcolor
    - scikit-image