name: curla
channels:
  - defaults
dependencies:
  - python=3.7.9
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - pip
  - pip:
    - termcolor
    - gymnasium
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image
    - tqdm
    - opencv-python
    - numpy